#!/usr/bin/env python3
"""File Firestore devFeedback notes into the expectation pages.

Called by scripts/fetch-feedback.sh. Kept separate so the filing can be
re-run against a saved JSON dump without hitting the network again.

The notes go into their own section, rebuilt on every run, between the
generated tables and the hand-written ground truth. That ordering is
deliberate: the pages already have two owners — the recorder writes the top,
the rider writes the bottom — and this is a third that must not tread on
either.
"""
import json
import pathlib
import sys
from collections import defaultdict

EXPECTATIONS = pathlib.Path(__file__).resolve().parent.parent / "openWaterTests" / "Expectations"
NOTES_MARKER = "<!-- Anything below this line is yours. Re-recording will not touch it. -->"
FEEDBACK_START = "<!-- feedback:start -->"
FEEDBACK_END = "<!-- feedback:end -->"


def value(field):
    """Unwrap one Firestore typed value."""
    if field is None:
        return None
    for key in ("stringValue", "integerValue", "doubleValue", "booleanValue"):
        if key in field:
            v = field[key]
            if key == "integerValue":
                return int(v)
            if key == "doubleValue":
                return float(v)
            return v
    return None


def render(notes):
    """One session's notes as markdown, newest first."""
    out = [FEEDBACK_START, "", "## Feedback from the device", ""]
    out.append(f"_{len(notes)} note(s), pulled from Firestore. "
               "Each carries the numbers the app was showing when it was written._")
    out.append("")
    for n in sorted(notes, key=lambda n: n.get("createdAt", ""), reverse=True):
        when = (n.get("createdAt") or "")[:16].replace("T", " ")
        out.append(f"### {n.get('verdict', '?')} — {when}")
        out.append("")
        text = (n.get("text") or "").strip()
        for line in text.splitlines() or [""]:
            out.append(f"> {line}")
        out.append("")
        out.append(
            f"_At the time: {n.get('runsDownwind', '?')} downwind · "
            f"{n.get('runsReaching', '?')} reaching · {n.get('runsUpwind', '?')} upwind, "
            f"from {n.get('stretches', '?')} stretches and {n.get('flights', '?')} flights. "
            f"Analysis v{n.get('analysisVersion', '?')}, {n.get('appVersion', '?')}._"
        )
        out.append("")
    out.append(FEEDBACK_END)
    return "\n".join(out)


def splice(page, block):
    """Put the block just *below* the notes marker, replacing any previous one.

    Below, not above. Everything above the marker is regenerated by
    scripts/record-expectations.sh, so feedback placed there would be wiped
    the next time the analysis changed — which is exactly when the feedback
    matters most. Below it, the recorder preserves it verbatim.
    """
    text = page.read_text()

    # Drop the previous feedback section, wherever it was.
    if FEEDBACK_START in text and FEEDBACK_END in text:
        head, rest = text.split(FEEDBACK_START, 1)
        text = head + rest.split(FEEDBACK_END, 1)[1].lstrip("\n")

    if NOTES_MARKER in text:
        head, tail = text.split(NOTES_MARKER, 1)
        page.write_text(f"{head.rstrip()}\n\n{NOTES_MARKER}\n\n{block}\n{tail.rstrip()}\n")
    else:
        page.write_text(f"{text.rstrip()}\n\n{block}\n")


def main():
    raw = json.loads(pathlib.Path(sys.argv[1]).read_text())
    documents = raw.get("documents", [])
    if not documents:
        print("No feedback yet.")
        return

    by_session = defaultdict(list)
    for doc in documents:
        note = {k: value(v) for k, v in doc.get("fields", {}).items()}
        by_session[note.get("session") or "unknown"].append(note)

    unfiled = []
    for session, notes in sorted(by_session.items()):
        page = EXPECTATIONS / f"{session}.md"
        if page.exists():
            splice(page, render(notes))
            print(f"{session}: {len(notes)} note(s)")
        else:
            unfiled.extend(notes)
            print(f"{session}: {len(notes)} note(s) — no page, filing as unfiled")

    if unfiled:
        page = EXPECTATIONS / "unfiled-feedback.md"
        page.write_text(
            "# Feedback with no matching session page\n\n"
            "_Notes whose session title does not match a `test-N` page. "
            "Usually a session recorded on the device rather than one of the "
            "test set._\n\n" + render(unfiled) + "\n"
        )

    print(f"\nFiled into {EXPECTATIONS}")


if __name__ == "__main__":
    main()
